### ISSUE TITLE
Use external module in consequence

### ISSUE THREAD

**Issue by frauss** [mithunsatheesh/node-rules#36] opened 2015-06-05 18:43 UTC
I'm wondering if there's any way to use an external module inside of a consequence function?

I was hoping to be able to do something like the following:

```javascript
    {
		"condition" : function(R) {
			R.when(true)
		},
		"consequence" : function(R) {
			var guid_generator = require('uuid');
			this.RecordId = guid_generator.v4();
			R.next();
		}
    }
```

However, that seems to trigger a recursive loop with this error:

(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

I imagine this is because require() uses process.nextTick().

Forgive me if this is a naive question as I'm new to Node and Javascript.

Thanks,
Fred

**Comment by mithunsatheesh** [comment] 2015-06-06 14:47
Hi Fred,

I think there is no need to put the require statement inside the consequence function. It could be put outside.

    var guid_generator = require('uuid');

Let me know if the issue is repeating even after doing that change.

Regards,
Mithun Satheesh

**Comment by mithunsatheesh** [comment] 2015-06-08 03:42
Hi Fred,

Please reopen this issue incase you face further problems after following my previous comment. Right now I am closing this as I think moving the require out of the consequence will fix it. 

This will certainly not fix the issue if we are considering the export/import abilty of the rules. I have mentioned the same case in the wiki prepared.
Refer: https://github.com/mithunsatheesh/node-rules/wiki/Exporting-and-Importing-Rules

Regards,
Mithun Satheesh

**Closed by mithunsatheesh** 2015-06-08 03:42 UTC

**Comment by frauss** [comment] 2015-06-08 15:21
Hi Mithun,

Unfortunately it is the export/import case I'm trying to deal with. I'm
storing rules in a Mongo Db instance.

Looks like I may be out of luck here.

Fred

**Comment by mithunsatheesh** [comment] 2015-06-09 03:22
Hi Fred,

With the current format used for the rules, its impossible to find a proper way to serialize as the rules are js objects with functions as property values. When you serialize, you will loose the closure relationships for conditions and consequnces - which is your exact case. I have opened another issue to track this.

**Comment by frauss** [comment] 2015-06-09 18:04
Mithun,

Thanks for the reply. I wound up finding a work around for this by
attaching the module references to the input object in a known field.

First, I establish my 'fact' object as a field on the input object:

var inputObject = {};
inputObject.fact = request.body;

Then given an array of module names like this:

var requiredModules = [{
fieldName: "guidGenerator",
moduleName: 'uuid'
},
{
fieldName: 'sprintf',
moduleName: 'sprintf'
}];

I create a modules field on the input object like this:

inputObject.modules = {};
for (var i = 0; i < rulesCollection.modules.length; i++) {

inputObject.modules[requiredModules[i].fieldName] = require(requiredModules[
i].moduleName);

}

I can then refer to these in my rules like this:

function(R) {

this.fact.RecordId = this.modules.guidGenerator.v4();

this.fact.IPTCMetadata.Description = this.modules.sprintf.sprintf("%s Photo
from user %s",

this.fact.IPTCMetadata.Description, this.fact.IncomingMetadata.User);

R.next();

}

Seems to work fine and the main caveat is I need to make sure all the
modules referenced in requiredModules are available. Not likely a general
purpose solution but something I can work with.

Fred

**Comment by mithunsatheesh** [comment] 2015-06-10 07:42
Great! Looks like a good workaround at first look. Injecting the dependent modules via the facts will do the trick. 

It would be great if you could document this workaround in the wiki:
https://github.com/mithunsatheesh/node-rules/wiki/Exporting-and-Importing-Rules

**Comment by frauss** [comment] 2015-06-15 14:32
Not sure if I documented in properly but I did add the workaround to the
wiki page.

Feel free to edit it as you see fit.

Fred

**Comment by mithunsatheesh** [comment] 2015-06-16 04:01
Great! Thank you :+1:
